name: model_catalogs
channels:
  - conda-forge
dependencies:
  - python=3.8  # this is required for the dev tools/precommit stuff
  - pytest
  - alphashape
  - appdirs
  - cf_xarray
  - dask
  - flake8
  - extract_model
  - h5netcdf
  # - intake
  # - intake-xarray
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib-base
  - netcdf4
  - numpy
  # - openssl<3.0  # NOMADS server for RTOFS doesn't work with openssl 3.0
  - pandas
  - pip
  # - pyproj
  - shapely
  - xarray
  - pip:  # install from github to get recent PRs I contributed
    # - git+https://github.com/axiom-data-science/extract_model.git
    - git+https://github.com/intake/intake-xarray.git
    #- git+https://github.com/intake/intake.git
    - git+https://github.com/intake/intake.git@d28391c54c875a47bf34f640e46c5f68109ba8b5
    #- git+https://github.com/axiom-data-science/extract_model.git
    - siphon  # can get from conda-forge but isn't recognized
    - datetimerange
    # - intake-nested-yaml-catalog
